[tool.poetry]
name = "ohtumini"
version = "0.1.0"
description = ":)"
authors = ["Juuso Saavalainen <juuso.saavalainen@helsinki.fi>"]

[tool.poetry.dependencies]
python = "^3.8"
coverage = "^6.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
coverage = "^6.5.0"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
Footer
